use sim_codec_classfile::{
    ByteReader, CodeException, ConstantPool, InstructionId, Opcode, decode_instructions,
};
use sim_kernel::SourceId;
use sim_lib_lang_jvm::{
    FusedHandler, JvmInstructionPolicy, JvmInstructionSemantics, JvmSlotKind, prepare_code,
    prepare_fusions,
};

const NONE: &[JvmSlotKind] = &[];

struct Policy;
impl JvmInstructionPolicy for Policy {
    fn semantics(_opcode: Opcode) -> Option<JvmInstructionSemantics> {
        Some(JvmInstructionSemantics {
            pops: NONE,
            pushes: NONE,
            safepoint: false,
        })
    }
}

fn pool() -> ConstantPool {
    ConstantPool::decode(&mut ByteReader::new(&[0, 1], 1), 61).unwrap()
}

fn prepared(
    bytes: &[u8],
    handlers: &[CodeException],
) -> sim_lib_machine::LocatedCode<sim_lib_lang_jvm::PreparedJvmPolicy> {
    let decoded = decode_instructions(bytes, 61, &pool()).unwrap();
    prepare_code::<Policy>(
        &decoded,
        bytes.len(),
        handlers,
        SourceId("fusion-test".into()),
    )
    .unwrap()
}

#[test]
fn generated_fusions_expand_exactly_and_retain_every_map() {
    let bytes = [
        Opcode::Iload0 as u8,
        Opcode::Iload1 as u8,
        Opcode::Iadd as u8,
        Opcode::Iconst2 as u8,
        Opcode::Imul as u8,
        Opcode::Return as u8,
    ];
    let code = prepared(&bytes, &[]);
    let first = prepare_fusions(&code);
    let second = prepare_fusions(&code);
    assert_eq!(
        first, second,
        "generation and selection must be deterministic"
    );
    assert_eq!(first.len(), 2);
    assert_eq!(first[0].handler(), FusedHandler::LoadPairAdd);
    assert_eq!(
        first[0].expansion(),
        &[InstructionId(0), InstructionId(1), InstructionId(2)]
    );
    assert_eq!(first[1].handler(), FusedHandler::ConstMultiply);
    assert_eq!(first[1].expansion(), &[InstructionId(3), InstructionId(4)]);
    for fusion in first.iter() {
        assert_eq!(fusion.expansion().len(), fusion.sources().len());
        assert_eq!(fusion.expansion().len(), fusion.work_map().len());
        assert_eq!(fusion.expansion().len(), fusion.root_map().len());
        for (map_index, instruction) in fusion.expansion().iter().enumerate() {
            let original = code.instruction(code.cursor(*instruction).unwrap());
            assert_eq!(&fusion.sources()[map_index], original.location());
            assert_eq!(
                fusion.work_map()[map_index],
                original.instruction().work_charge()
            );
            assert_eq!(
                fusion.root_map()[map_index],
                original.instruction().root_effect()
            );
        }
    }
}

#[test]
fn generated_check_refuses_handler_and_branch_boundaries() {
    let sequence = [
        Opcode::Iload0 as u8,
        Opcode::Iload1 as u8,
        Opcode::Iadd as u8,
        Opcode::Return as u8,
    ];
    let handler = CodeException {
        start_pc: 0,
        end_pc: 3,
        handler_pc: 3,
        catch_type: 0,
    };
    assert!(prepare_fusions(&prepared(&sequence, &[handler])).is_empty());

    let branched = [
        Opcode::Goto as u8,
        0,
        4,
        Opcode::Iload0 as u8,
        Opcode::Iload1 as u8,
        Opcode::Iadd as u8,
        Opcode::Return as u8,
    ];
    assert!(
        prepare_fusions(&prepared(&branched, &[])).is_empty(),
        "an incoming target inside a candidate must exclude fusion"
    );
}

#[test]
fn checked_in_generated_source_is_byte_identical_to_regeneration() {
    let checked = include_str!("../src/superinstructions_generated.rs");
    assert!(
        checked
            .starts_with("// @generated by build.rs from superinstructions.toml; DO NOT EDIT.\n")
    );
    assert_eq!(checked.matches("FusedDefinition { handler:").count(), 2);
}
