// @generated by build.rs from superinstructions.toml; DO NOT EDIT.

/// Generated fused-handler identity.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum FusedHandler {
    /// Profile-selected `LoadPairAdd` sequence.
    LoadPairAdd,
    /// Profile-selected `ConstMultiply` sequence.
    ConstMultiply,
}

/// One declaratively generated straight-line fusion definition.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct FusedDefinition { pub handler: FusedHandler, pub opcodes: &'static [Opcode] }

/// Bounded fusion family, in deterministic manifest order.
pub const FUSED_DEFINITIONS: &[FusedDefinition] = &[
    FusedDefinition { handler: FusedHandler::LoadPairAdd, opcodes: &[Opcode::Iload0, Opcode::Iload1, Opcode::Iadd, ] },
    FusedDefinition { handler: FusedHandler::ConstMultiply, opcodes: &[Opcode::Iconst2, Opcode::Imul, ] },
];
